# Generated by Django 5.2 on 2025-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0002_remove_account_username_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
