# Generated by Django 5.1.7 on 2025-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0002_remove_account_username_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
