# Generated by Django 5.1.7 on 2025-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0003_account_verification_token_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
