# Generated by Django 5.1.7 on 2025-04-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0004_account_is_online'),
        ('Spotify', '0004_alter_song_cover_image'),
    ]

    operations = [
    ]
