# Generated by Django 5.1.7 on 2025-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0005_merge_20250420_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
