# Generated by Django 5.1.7 on 2025-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0006_remove_song_audio_file_remove_song_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
