# Generated by Django 5.1.7 on 2025-04-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0007_video_video_file_url_alter_video_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
