# Generated by Django 5.1.7 on 2025-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spotify', '0009_song_is_approved_video_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
